services:
  frontend:
    container_name: psitest-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - psitest
    env_file: ".env"
networks:
  psitest:
    external: true